# docker-compose.yml
# Docker Compose file to build and run the frontend container.
# - Maps container port 80 to host port 8080.
# - Uses local Dockerfile to build the image.

version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:80"
