version: '3.8'

services:
  webmap:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    container_name: 3d-webmap
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/processed:/app/processed
      - ./backend/temp:/app/temp
    environment:
      - NODE_ENV=development
    expose:
      - "3000"
    container_name: 3d-webmap-backend
    restart: unless-stopped